# conf/model/domain_adapt/wgan.yaml

visual_da:
  _target_: mdt.models.domain_adapt.wgan.WGAN_GP
  in_dim: 512  # trans_enc:1536, res_perceptual:1024, voltron_perceptual:1152, action_emb:10*512
  reduce_scale: 2
  ndims: 2
  gamma: 10

action_da:
  _target_: mdt.models.domain_adapt.wgan.WGAN_GP
  in_dim: 512  # trans_enc:1536, res_perceptual:1024, voltron_perceptual:1152, action_emb:10*512
  reduce_scale: 2
  ndims: 3
  gamma: 10

use_da_visual: 'false'  # static,gripper,both,false
use_da_act: true
