# conf/model/domain_adapt/wgan.yaml

visual_da:
  _target_: mdt.models.domain_adapt.wgan.WGAN_GP
  in_dim: "512*1,"  # trans_enc:1536, res_perceptual:1024, voltron_perceptual:1152, action_emb:10*512
  in_ndim: "2*1,"
  gamma: 10

action_da:
  _target_: mdt.models.domain_adapt.wgan.WGAN_GP
  in_dim: "1536*12,"  # ori:`1536*12`, trans_enc:1536, res_perceptual:1024, voltron_perceptual:1152, action_emb:10*512
  in_ndim: "2*12,"  # ori:`2*12`
  gamma: 10
  num_layers: 12  # v:6 layers, k:6 layers
  use_ada: true
  use_cond_dist: false

use_da_visual: 'false'  # static,gripper,both,false
use_da_act: true
act_loss_from: "k,v"  # ori:`k,v`, choices:`k`,`v`,`q`,`sa`,`ca`
act_layers: 6  # ori:6
act_weights: "ca"  # ori:`ca`, choices:`ca`,`adapter`
