# conf/model/domain_adapt/wgan.yaml

visual_da:
  _target_: mdt.models.domain_adapt.wgan.WGAN_GP
  in_dim: "512*1,"  # trans_enc:1536, res_perceptual:1024, voltron_perceptual:1152, action_emb:10*512
  in_ndim: "2*1,"
  gamma: 10

action_da:
  _target_: mdt.models.domain_adapt.wgan.WGAN_GP
  in_dim: "512*6,"  # ori:`1536*12`, kv:(1536,2), q:(512,3), attn:(512,3), softmax:(8,4)
  in_ndim: "3*6,"  # ori:`2*12`
  gamma: 10
  num_layers: 6  # v:6 layers, k:6 layers
  use_ada: true
  use_cond_dist: false

use_da_visual: 'both'  # static,gripper,both,false
use_da_act: true
act_loss_from: "attn"  # ori:`k,v`, choices:`k`,`v`,`q`,`sa`,`ca`,`attn`,`softmax`
act_layers: 6  # ori:6
act_weights: "adapter"  # ori:`ca`, choices:`ca`,`adapter`
