# conf/da_d_slurm.yaml
defaults:
  - callbacks: calvin
  - datamodule: calvin_da
  - model: mdtv_da_enc # mdt_agent, mdtv_agent, mdtv_da_enc
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

root_home: /public/home/group_xudong/gavinyuan
source_root_data_dir: ${root_home}/code/mdt24rss_fork/dataset/task_ABC_D
target_root_data_dir: ${root_home}/code/mdt24rss_fork/dataset/task_D_D
lang_folder: lang_clip_resnet50
vis_clip_model_name: ViT-B/16
clip_lang_model_name: ViT-B/32

log_dir: ${root_home}/code/mdt24rss_fork/logs
slurm: true  # slurm
min_window_size: 21
max_window_size: 50
future_range: 29
seed: 242
device: 'cuda'
batch_size: 64  # ori:128
devices: 4
goal_window_size: 1
act_dim: 7
obs_dim: 384
goal_dim: 512
obs_seq_len: 1
act_seq_len: 10
multistep: 10
p_last_state: 0
gen_img_res: 112
max_epochs: 19
rollout_lh_skip_epochs: 6
window_sampling_strategy: 'geometric'
num_tokens_voltron: 3
num_workers: 12
img_gen_frame_diff: 3
use_extracted_rel_actions: true
benchmark_name: calvin_d


trainer:
  gpus: ${devices}
  precision: bf16
  max_epochs: ${max_epochs}
  sync_batchnorm: false
  accelerator: auto
  limit_train_batches: 1000
  limit_val_batches: 4

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  offline: true  # slurm
  save_dir: .
  name: logger
  group: mdt
  log_model: false
  project: ${benchmark_name} # calvin_vision
  entity: gavinyuan
  id: ???


hydra:
  run:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
          - datamodule.source_root_data_dir
          - datamodule.target_root_data_dir
          - trainer.gpus
          - datamodule.num_workers
          - trainer.limit_train_batches
          - trainer.limit_val_batches
