# conf/callbacks/calvin.yaml
defaults:
  - rollout_lh: default
  - checkpoint: lh_sr  # ori:lh_sr
  - manually_ckpt: save_model


ema:
  _target_: mdt.callbacks.ema.EMA
  decay: 0.999
  start_step: 0
  save_ema_weights_in_callback_state: True
  evaluate_ema_weights_instead: True

  power: 0.6666666666666666
  inv_gamma: 1.0
  min_value: 0.0
  max_value: 0.9999
