# conf/datamodule/calvin_da.yaml
defaults:
  - datasets: clear_vl_calvin
  - transforms: calvin_transforms
_target_: mdt.datasets.hulc_da_data_module.HulcDomainAdaptDataModule
_recursive_: false

root_data_dir: ${root_data_dir}
action_space: 7
action_max: [1., 1., 1., 1., 1., 1., 1.,]
action_min: [-1., -1., -1., -1., -1., -1., -1]
shuffle_val: false


observation_space:
  rgb_obs: ['rgb_static', 'rgb_gripper', 'gen_static', 'gen_gripper']
  depth_obs: []
  state_obs: ['robot_obs']
  actions: ['rel_actions']
  language: ['language']

proprioception_dims:
  n_state_obs: 8
  keep_indices: [[0, 7], [14,15]]
  robot_orientation_idx: [3, 6]
  normalize: True
  normalize_robot_orientation: True
